language: go

services:
- docker

stages:
  - name: build go
    if: branch != master
  - name: build docker image
    if: (NOT type IN (pull_request)) AND (branch = master)

jobs:
  include:
    - stage: build go
      script: make build
    - stage: build docker image
      script: make build-docker
      script: docker login -u $DOCKER_USER -p $DOCKER_PASS
      script: make push

